import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <div>
//       <Navbar />
//       <main>{children}</main>
//       <Footer />
//     </div>
      </body>
    </html>
  );
}

// import React from 'react';
// import Navbar from '../components/Navbar';
// import Footer from '../components/Footer';

// export default function Layout({ children }) {
//   return (
//     <div>
//       <Navbar />
//       <main>{children}</main>
//       <Footer />
//     </div>
//   );
// }

